/**
 * Geocode all RKM branch centres using Nominatim (OpenStreetMap).
 * Saves progress to a checkpoint file and skips already-geocoded entries.
 * Outputs: public/rkm-centres/data/centres.js  (window.CENTRES_DATA)
 *
 * Run: node scripts/geocode-centres.mjs
 * Safe to re-run — resumes from checkpoint.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const INPUT      = "public/branch_centres.json";
const OUTDIR     = "public/rkm-centres/data";
const CHECKPOINT = join(OUTDIR, "centres_checkpoint.json");
const OUTPUT     = join(OUTDIR, "centres.js");

const centres = JSON.parse(readFileSync(INPUT, "utf-8"));

const FLAG = {
  "India":"🇮🇳","USA":"🇺🇸","Bangladesh":"🇧🇩","South Africa":"🇿🇦",
  "Australia":"🇦🇺","Brazil":"🇧🇷","Malaysia":"🇲🇾","Canada":"🇨🇦",
  "Mauritius":"🇲🇺","Sri Lanka":"🇱🇰","Argentina":"🇦🇷","Fiji":"🇫🇯",
  "France":"🇫🇷","Germany":"🇩🇪","Ireland":"🇮🇪","Japan":"🇯🇵",
  "Nepal":"🇳🇵","Netherlands":"🇳🇱","New Zealand":"🇳🇿","Philippines":"🇵🇭",
  "Russia":"🇷🇺","Singapore":"🇸🇬","Switzerland":"🇨🇭",
  "United Kingdom":"🇬🇧","Zambia":"🇿🇲",
};

function buildQuery(c) {
  const nameParts = c.name.split(",");
  const city = nameParts.length > 1 ? nameParts.slice(1).join(",").trim() : "";
  if (c.country === "India" && c.state) {
    return city ? `${city}, ${c.state}, India` : `${c.state}, India`;
  }
  if (c.address) {
    const lines = c.address.split("\n").map(l => l.trim()).filter(Boolean);
    if (lines.length > 1) return lines[lines.length - 1];
  }
  return city ? `${city}, ${c.country}` : c.country;
}

async function geocode(query) {
  try {
    const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(query)}&format=json&limit=1`;
    const res = await fetch(url, {
      headers: { "User-Agent": "RKM-Centres-Map/1.0 (museum app)" },
    });
    const text = await res.text();
    if (!text.trim().startsWith("[") && !text.trim().startsWith("{")) return null;
    const data = JSON.parse(text);
    if (data.length > 0) return { lat: parseFloat(data[0].lat), lng: parseFloat(data[0].lon) };
  } catch { /* network or parse error */ }
  return null;
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

mkdirSync(OUTDIR, { recursive: true });

// Load checkpoint
const checkpoint = existsSync(CHECKPOINT)
  ? JSON.parse(readFileSync(CHECKPOINT, "utf-8"))
  : {};

console.log(`Geocoding ${centres.length} centres (${Object.keys(checkpoint).length} already done)…`);

let ok = 0, fail = 0, skipped = 0;
const results = [];

for (let i = 0; i < centres.length; i++) {
  const c = centres[i];
  const key = String(i);

  // Resume from checkpoint
  if (checkpoint[key]) {
    results.push(checkpoint[key]);
    skipped++;
    if (checkpoint[key].lat !== null) ok++; else fail++;
    continue;
  }

  const query = buildQuery(c);
  let geo = await geocode(query);

  if (!geo && c.country !== "India") {
    const city = c.name.split(",").slice(1).join(",").trim();
    if (city) { await sleep(1050); geo = await geocode(`${city}, ${c.country}`); }
  }
  if (!geo && c.country === "India" && c.state) {
    await sleep(1050); geo = await geocode(`${c.state}, India`);
  }
  if (!geo) {
    await sleep(1050); geo = await geocode(c.country);
  }

  const entry = {
    id: i + 1,
    name: c.name,
    country: c.country,
    state: c.state || null,
    address: c.address || null,
    phone: c.phone || null,
    email: c.email || null,
    flag: FLAG[c.country] || "🏛️",
    type: c.name.toLowerCase().includes("mission") ? "mission" : "math",
    lat: geo ? geo.lat : null,
    lng: geo ? geo.lng : null,
  };

  checkpoint[key] = entry;
  results.push(entry);

  if (geo) { ok++; console.log(`  ✓ [${i+1}/${centres.length}] ${c.name}  →  ${geo.lat.toFixed(3)}, ${geo.lng.toFixed(3)}`); }
  else      { fail++; console.log(`  ✗ [${i+1}/${centres.length}] ${c.name}  — no result`); }

  // Save checkpoint every 10 entries
  if ((i + 1) % 10 === 0) writeFileSync(CHECKPOINT, JSON.stringify(checkpoint, null, 2));

  await sleep(1050);
}

// Final checkpoint save
writeFileSync(CHECKPOINT, JSON.stringify(checkpoint, null, 2));

// Write output JS
const js = `// Auto-generated by scripts/geocode-centres.mjs — do not edit manually\nwindow.CENTRES_DATA = ${JSON.stringify(results, null, 2)};\n`;
writeFileSync(OUTPUT, js, "utf-8");

console.log(`\n${"─".repeat(55)}`);
console.log(`Done. ${ok} geocoded, ${fail} without coordinates. (${skipped} from cache)`);
console.log(`Output: ${OUTPUT}`);
